name: check

on:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - name: get-latest-version
      run: |
        VERSION="$(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/main/binary-amd64/ | grep wine-stable | sed 's|_| |g;s|~| |g' | awk '{print $5}' | tail -n1)"
        last=$(tail -n1 .build | awk '{print $4}')

        if [ "$last" != "$VERSION" ]; then
          echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build
        fi
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Trigger build for new version
        branch: main
